version: '3.8'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
    ports:
      - "9300:8000"  # Maps port 8000 of the container to port 8000 on the host
